[package]
name = "jpeg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bmp = "0.5.0"
ndarray = "0.15.4"
ndarray-linalg = { version = "0.14", features = ["openblas-static"] }
